i3: remove i3pystatus

diff --git a/.config/i3/status b/.config/i3/status
--- a/.config/i3/status
+++ b/.config/i3/status
@@ -1,114 +1,12 @@
-#!/usr/bin/env python3
-import os
-import pathlib
+#!/usr/bin/env zsh
 
-import i3pystatus
+setopt ERREXIT PIPEFAIL NOUNSET
 
-I3STATUSRS_CONFIG_FILE = pathlib.Path(
-    "~/.config/i3/i3status-rs.config.toml"
-).expanduser()
+CONFIG_FILE=${0:h}/i3status-rs.config.toml
 
-# Replace ourselves with i3status-rs if present
-if I3STATUSRS_CONFIG_FILE.exists() and any(
-    pathlib.Path(path, "i3status-rs").exists()
-    for path in os.environ["PATH"].split(os.pathsep)
-):
-    os.execlp("i3status-rs", "i3status-rs", I3STATUSRS_CONFIG_FILE)
-
-###################
-# DEPENDENCIES    #
-# - basiciw       #
-# - i3pystatus    #
-# - libpulseaudio #
-# - netifaces     #
-# - pyyaml        #
-###################
-
-##########
-# COLORS #
-##########
-
-GREEN = "#00FF00"
-RED = "#FF0000"
-YELLOW = "#FFFF00"
-
-##########
-# HEADER #
-##########
-
-DEFAULT_HINTS = {"separator": False}
-
-
-def hints(new_hints=None):
-    result = DEFAULT_HINTS.copy()
-    result.update(new_hints or {})
-    return result
-
-
-status = i3pystatus.Status(standalone=True)
-
-#########
-# CLOCK #
-#########
-
-status.register("clock", format="%d-%m-%Y %H:%M:%S", hints=hints())
-
-#######
-# CPU #
-#######
-
-status.register("load", format="{avg1}", hints=hints())
-status.register("temp", format="CPU {temp:.0f}°C", hints=hints())
-
-###########
-# BATTERY #
-###########
-
-status.register(
-    "battery",
-    format="{status}{percentage:.2f}%",
-    alert=True,
-    alert_percentage=5,
-    full_color=GREEN,
-    charging_color=YELLOW,
-    critical_color=RED,
-    status={"DIS": "↓", "CHR": "↑", "FULL": ""},
-    hints=hints(),
-)
-
-############
-# INTERNET #
-############
-
-status.register(
-    "network",
-    interface="wlp3s0",
-    format_up="{essid} {quality:03.0f}%",
-    format_down="Wi-Fi DOWN!!!",
-    color_up=GREEN,
-    color_down=RED,
-    hints=hints(),
-)
-
-########
-# DISK #
-########
-
-status.register(
-    "disk",
-    path="/",
-    # format="{used}/{total}G [{avail}G]",)
-    format="{avail}G avail.",
-    hints=hints(),
-)
-
-#########
-# AUDIO #
-#########
-status.register("pulseaudio", format="VOL {volume}", hints=hints())
-
-##########
-# FOOTER #
-##########
-
-status.run()
+if [[ ${commands[i3status-rs]} ]]; then
+    exec i3status-rs $CONFIG_FILE
+else
+    printf "Could not find i3status-rs, exiting.\n" >&2
+    exit 1
+fi
